name: Build & Release VS Code Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      package:
        description: "Create VSIX package"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # only on tag
      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          CURRENT=$(node -p "require('./package.json').version")

          if [ "$VERSION" != "$CURRENT" ]; then
            npm version $VERSION --no-git-tag-version
          else
            echo "Version already set, skipping"
          fi

      - run: npm run build

      # package if:
      # - tag build
      # - OR manual with package=true
      - name: Package extension
        if: startsWith(github.ref, 'refs/tags/') || inputs.package == 'true'
        run: npx vsce package

      # upload artifact for manual runs
      - name: Upload VSIX
        if: github.event_name == 'workflow_dispatch' && inputs.package == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: "*.vsix"

      # create release only on tag
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
